version: "3.8"

services:
  app:
    build: .
    container_name: python_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:8001 # Use service name instead of localhost
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.1
    container_name: mlflow_server
    ports:
      - "8001:8001"
    volumes:
      - ./mlruns:/mlruns # Persistent storage for MLflow experiments
    environment:
      - BACKEND_STORE_URI=sqlite:///mlflow.db # Store experiments in a local SQLite database
      - ARTIFACT_ROOT=/mlruns # Location for saving artifacts
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns --host 0.0.0.0 --port 8001
