version: "3.8"

services:
  app:
    build: .
    container_name: python_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env # Load environment variables from the .env file
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.1
    container_name: mlflow_server
    ports:
      - "8001:8001"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - BACKEND_STORE_URI=sqlite:///mlflow.db
      - ARTIFACT_ROOT=/mlruns
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns --host 0.0.0.0 --port 8001
