name: Docker Compose CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-docker-compose:
    runs-on: self-hosted # Runs on your GitHub Runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build and start containers
        run: docker compose up --build

      - name: Check running containers
        run: docker ps -a

      - name: Wait for application to be ready
        run: sleep 10 # Adjust this if your app takes longer to start

      - name: Test application endpoint
        run: |
          curl --fail http://localhost:8000 || (echo "App failed to start" && exit 1)
