name: Docker Compose CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-docker-compose:
    runs-on: self-hosted # Runs on your GitHub Runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Check running containers
        run: docker ps -a
